language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
install: composer install --prefer-source --no-interaction
cache:
  directories:
  - vendor
notifications:
  slack: languageleap:iSnqN0nELulTlljZCPYKbhz3
